### PR TITLE
Use PG instead of sqlite

### PR DESCRIPTION
**Pull request by kimh**

### CODE REVIEW

**Review by keybits — APPROVED** [review]
LGTM

**Comment by FelicianoTech** [comment]
Why?

**Comment by zzak** [comment]
@felicianotech I can't speak for Kim, but I can say that more users are going to be using PG for their applications -- even in their test environment and CI. The reason is just to be closer to reality.

Even though sqlite is a great option because it's fast and efficient for tests... I think using the same environment as production will catch bugs sooner. Also, there are a number of features that sqlite just doesn't support and PG does.

If your app doesn't rely on these features, or any kind of indexing, and you're just doing some simple unit tests then sqlite is probably fine. But this is going to be less likely for apps and more so for libraries running on CI.

**Comment by ndintenfass** [comment]
+1 for pg when paired with rails to better emulate likely user scenario

**Comment by FelicianoTech** [comment]
When originally creating these projects, the idea was to use different databases and deployment methods for each project so that we can demo examples of each. If Rails devs are highly likely to use PG, that's great, but then we should have an example of using sqlite somewhere else so that we have the example. If all/90% of the demo all use the same tools, then we're not providing much of a spread.

**Comment by kimh** [comment]
> using sqlite somewhere else so that we have the example

I agree with the idea to cover many types of DB but a tutorial for sqlite is not so valuable. Users don't have to do anything special to make sqlite work in 2.0: it's just a matter of updating `database.yml` and the rest is taken care by Rails.

I'll mention in https://circleci.com/docs/2.0/language-ruby/ that users don't need to do special thing if they are using sqlite.

**Pull request merged**
